import { useState } from 'react';                                                                                                                                                                                  
                                                                                                                                                                                                                   
const Hero = () => {                                                                                                                                                                                               
  const [activeTab, setActiveTab] = useState('Senior Manager / Platform Lead');                                                                                                                                    
                                                                                                                                                                                                                   
  const handleTabChange = (tab) => {                                                                                                                                                                               
    setActiveTab(tab);                                                                                                                                                                                             
  };                                                                                                                                                                                                               
                                                                                                                                                                                                                   
  return (                                                                                                                                                                                                         
    <div className="hero-container">                                                                                                                                                                               
      <div className="tab-container">                                                                                                                                                                              
        <button onClick={() => handleTabChange('Senior Manager / Platform Lead')}>Senior Manager / Platform Lead</button>                                                                                          
        <button onClick={() => handleTabChange('Infrastructure Architect')}>Infrastructure Architect</button>                                                                                                      
        <button onClick={() => handleTabChange('Full Master View')}>Full Master View</button>                                                                                                                      
      </div>                                                                                                                                                                                                       
      <h1>{activeTab}</h1>                                                                                                                                                                                         
      <p>{activeTab === 'Senior Manager / Platform Lead' ? 'Description for Senior Manager / Platform Lead' : activeTab === 'Infrastructure Architect' ? 'Description for Infrastructure Architect' : 'Description 
for Full Master View'}</p>                                                                                                                                                                                         
      <button>Download Tailored Resume</button>                                                                                                                                                                    
      <button>View Architecture Cases</button>                                                                                                                                                                     
      <button>GitHub</button>                                                                                                                                                                                      
      <button>LinkedIn</button>                                                                                                                                                                                    
      <p>🟢 Available for Senior Infrastructure / Platform Lead Roles</p>                                                                                                                                          
    </div>                                                                                                                                                                                                         
  );                                                                                                                                                                                                               
};                                                                                                                                                                                                                 
                                                                                                                                                                                                                   
export default Hero;  
